import Link from "next/link";
import { notFound } from "next/navigation";

const operator = {
  name: process.env.LEGAL_OPERATOR_NAME || "[Vollständiger Betreibername vor Veröffentlichung erforderlich]",
  trading: process.env.LEGAL_TRADING_NAME || "AmtHero24",
  status: process.env.LEGAL_OPERATOR_STATUS || "[Rechtsform/Betreiberstatus vor Veröffentlichung erforderlich]",
  address: process.env.LEGAL_SERVICE_ADDRESS || "[Ladungsfähige Anschrift vor Veröffentlichung erforderlich]",
  country: process.env.LEGAL_COUNTRY || "[Land vor Veröffentlichung erforderlich]",
  info: process.env.LEGAL_EMAIL_INFO || "info@amthero24.de",
  support: process.env.LEGAL_EMAIL_SUPPORT || "support@amthero24.de",
};

const pages = {
  impressum: ["Impressum", <><p className="warning">Entwurf nach § 5 DDG. Veröffentlichung bleibt gesperrt, bis Betreiberstatus, ladungsfähige Anschrift, Register-/USt.-Daten soweit einschlägig, zuständige Aufsicht und VSBG-Entscheidung geprüft sind.</p><h2>Anbieter</h2><address><b>{operator.name}</b><br/>{operator.trading}<br/>{operator.status}<br/>{operator.address}<br/>{operator.country}</address><h2>Kontakt</h2><p>E-Mail: <a href={`mailto:${operator.info}`}>{operator.info}</a><br/>Support: <a href={`mailto:${operator.support}`}>{operator.support}</a></p><h2>Leistungsumfang</h2><p>AmtHero24 ist ein KI-gestützter Assistent für allgemeine Informationen, Erklärungen, Organisation, Formulierungshilfe und Erinnerungen. Keine Behörde, keine Rechts-, Steuer-, Finanz- oder medizinische Beratung und keine Vertretung.</p><h2>Verbraucherstreitbeilegung</h2><p>[VSBG-Erklärung vor Veröffentlichung anhand der tatsächlichen Unternehmenssituation festlegen.]</p></>],
  datenschutz: ["Datenschutzerklärung", <><p className="warning">DSGVO-Entwurf für Website und WhatsApp-Bot. Vor Veröffentlichung müssen tatsächliche Auftragsverarbeiter, Regionen, AV-Verträge und Drittlandtransfers bestätigt werden.</p><h2>Verantwortlicher</h2><p>{operator.name}, {operator.address}, {operator.country} · <a href={`mailto:${operator.info}`}>{operator.info}</a></p><h2>Website</h2><p>Die Vorabversion verwendet keine Analyse- oder Marketing-Tracker und lädt keine externen Schriftarten oder Video-Embeds. Technische Serverdaten werden nur für Betrieb, Sicherheit und Fehleranalyse verarbeitet.</p><h2>WhatsApp und Meta</h2><p>Wenn du Sam über WhatsApp kontaktierst, werden Nachrichten und technische Metadaten über die WhatsApp Cloud API verarbeitet. Meta ist für eigene Verarbeitungsvorgänge nach seinen Bedingungen verantwortlich. Die konkreten Rollen und Drittlandtransfermechanismen werden vor GO dokumentiert.</p><h2>Dokumente und Audio</h2><p>Dokument- und Audiodaten werden zur angeforderten Verarbeitung verwendet. Das Produktdesign sieht vor, Rohdateien nach der Verarbeitung nicht dauerhaft zu speichern. Inhalte dürfen nicht in CI oder allgemeinen Betriebslogs erscheinen.</p><h2>Hero Memory</h2><p>Wiederverwendbare persönliche Erinnerung wird nur nach separater Einwilligung gespeichert. Beta-Teilnahme und Memory-Einwilligung sind getrennte Entscheidungen.</p><h2>Rechte</h2><p>Je nach Voraussetzungen bestehen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit, Widerspruch und Widerruf einer Einwilligung sowie Beschwerde bei einer Datenschutzaufsichtsbehörde.</p></>],
  agb: ["AGB – Closed Beta", <><p className="warning">Diese Bedingungen sind für eine kostenlose, begrenzte Closed Beta vorbereitet. Bezahlte Leistungen, Entitlements und öffentlicher Signup sind nicht umfasst.</p><h2>Gegenstand</h2><p>AmtHero24 bietet während der Closed Beta einen KI-gestützten WhatsApp-Assistenten für administrative Alltagshilfe in Deutschland. Der Funktionsumfang kann sich während der Beta ändern.</p><h2>Kein Erfolg geschuldet</h2><p>Erklärungen, Entwürfe und Hinweise können fehlerhaft oder unvollständig sein. Nutzer müssen wichtige Angaben, Fristen, Beträge und Texte am Original prüfen.</p><h2>Nutzung</h2><p>Keine rechtswidrige Nutzung, keine missbräuchliche Automatisierung und keine Übermittlung von Daten Dritter ohne ausreichende Berechtigung.</p><h2>Verfügbarkeit</h2><p>Während der kostenlosen Beta besteht kein Anspruch auf unterbrechungsfreie Verfügbarkeit oder bestimmte Funktionen. Sicherheits- und Datenschutzgrenzen haben Vorrang.</p><h2>Beendigung</h2><p>Die Beta kann jederzeit beendet werden. Separate Datenschutzrechte und gesetzliche Ansprüche bleiben unberührt.</p></>],
  widerruf: ["Widerruf & Beta beenden", <><p>Wave 1 ist als kostenlose Closed Beta geplant. Die Teilnahme kann jederzeit ohne Begründung beendet werden. Soweit im Einzelfall ein gesetzliches Widerrufsrecht besteht, bleiben diese Rechte unberührt.</p><h2>Beta verlassen</h2><p>Nutze den vorgesehenen WhatsApp-Befehl zum Verlassen oder schreibe an <a href={`mailto:${operator.support}`}>{operator.support}</a>.</p><h2>Datenschutz getrennt</h2><p>Das Verlassen der Beta ist nicht automatisch eine vollständige Datenlöschung. Export, Löschung und Widerruf einer Memory-Einwilligung sind eigenständige Datenschutzfunktionen.</p></>],
  kontakt: ["Kontakt", <><h2>Allgemeine Fragen</h2><p><a href={`mailto:${operator.info}`}>{operator.info}</a></p><h2>Beta & technischer Support</h2><p><a href={`mailto:${operator.support}`}>{operator.support}</a></p><h2>Kein Notfallkanal</h2><p>AmtHero24 ist kein Notfalldienst. Bei akuter Gefahr oder medizinischem Notfall müssen die zuständigen Stellen in Deutschland kontaktiert werden.</p></>],
  beta: ["Closed-Beta-Hinweis", <><p className="warning">Admission ist aktuell deaktiviert. Diese Seite öffnet keinen Zugang.</p><h2>Begrenzter Test</h2><p>Wave 1 ist auf maximal fünf gleichzeitig zugelassene Nutzer ausgelegt. Teilnahme ist freiwillig und erfordert eine ausdrückliche Beta-Einwilligung.</p><h2>KI-Transparenz</h2><p>Sam ist ein KI-gestützter Assistent, kein Mensch. Wichtige Ergebnisse müssen vor Handlungen geprüft werden.</p><h2>Getrennte Einwilligungen</h2><p>Eine Beta-Einwilligung bedeutet nicht automatisch Zustimmung zur wiederverwendbaren Hero Memory.</p></>],
  "cookie-einstellungen": ["Cookie- & Datenschutzeinstellungen", <><p>Diese Vorabversion setzt keine Analyse-, Werbe- oder Social-Media-Tracker ein. Es werden keine externen Video-Embeds oder Schriftarten benötigt.</p><h2>Technisch notwendig</h2><p>Erforderliche Sicherheits- und Serverfunktionen können ohne Marketingprofiling betrieben werden. Werden später nicht notwendige Tracking-Technologien ergänzt, müssen sie vor Aktivierung eine geeignete Einwilligungssteuerung erhalten.</p></>],
  barrierefreiheit: ["Barrierefreiheit", <><p>AmtHero24 verfolgt für die Landingpage klare Tastaturbedienung, sichtbare Fokuszustände, semantische Struktur, ausreichenden Kontrast und Unterstützung für reduzierte Bewegung.</p><h2>Rückmeldung</h2><p>Barrieren können an <a href={`mailto:${operator.support}`}>{operator.support}</a> gemeldet werden.</p></>],
};

export async function generateMetadata({ params }) { const { legal } = await params; return { title: pages[legal]?.[0] || "AmtHero24" }; }
export default async function Legal({ params }) { const { legal } = await params; const page = pages[legal]; if (!page) notFound(); return <main id="main" className="legal"><Link href="/">← Zurück zu AmtHero24</Link><p className="eyebrow">AmtHero24 · Rechtliches</p><h1>{page[0]}</h1>{page[1]}</main>; }
